version: "1.0.0"
services:
  docker-hoster:
    image: dvdarias/docker-hoster
    container_name: docker-hoster
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /etc/hosts:/tmp/hosts
  mongodb:
    image: mongo:6.0.5
    container_name: mongodb
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh localhost:27017 --quiet
      interval: 5s
      timeout: 5s
      start_period: 5s
      retries: 3
    depends_on:
      - docker-hoster
    volumes:
      - ./initdb/data:/initdb/data
      - ./initdb/mongoimport.sh:/docker-entrypoint-initdb.d/mongoimport.sh:ro
  paccounts-backend:
    image: olezhuravlev/paccounts-backend:0.0.1
    container_name: paccounts-backend
    #    ports:
    #      - 8080:8080
    network_mode: host
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8080" ]
      interval: 5s
      timeout: 15s
      retries: 3
      start_period: 60s
